version: '3.8'

services:
  web:
    build: .
    command: sh -c 'sleep 3; alembic upgrade head && uvicorn sendcloud.apps.api_service:app --host 0.0.0.0 --port 5000'
    volumes:
      - .:/sendcloud
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://sendcloud:sendcloud@db:5435/sendcloud
    depends_on:
      - db
  scheduler-service:
    build: .
    command: sh -c 'sleep 3; alembic upgrade head && export PYTHONPATH=${PYTHONPATH}:./sendcloud && python sendcloud/apps/scheduler_service.py'
    volumes:
      - .:/sendcloud
    environment:
      - DATABASE_URL=postgresql+asyncpg://sendcloud:sendcloud@db:5435/sendcloud
      - SCHEDULER_TIME_INTERVAL=300
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5435
    environment:
      - POSTGRES_USER=sendcloud
      - POSTGRES_PASSWORD=sendcloud
      - POSTGRES_DB=sendcloud
    command: -p 5435

volumes:
  postgres_data:
