version: '3.8'

services:
  tests:
    build: .
    command: sh -c 'alembic upgrade head && export PYTHONPATH=${PYTHONPATH}:./sendcloud && pytest .'
    volumes:
      - .:/sendcloud
    environment:
      - DATABASE_URL=postgresql+asyncpg://sendcloud:sendcloud@db:5435/sendcloud
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5435
    environment:
      - POSTGRES_USER=sendcloud
      - POSTGRES_PASSWORD=sendcloud
      - POSTGRES_DB=sendcloud
    command: -p 5435

volumes:
  postgres_data: