version: '3.8'

services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn sendcloud.apps.main:app --host 0.0.0.0'
    volumes:
      - .:/sendcloud
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://sendcloud_db_user:sendcloud_db_password@db:5432/sendcloud_db
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=sendcloud_db_user
      - POSTGRES_PASSWORD=sendcloud_db_password
      - POSTGRES_DB=sendcloud_db

volumes:
  postgres_data: