"""init database

Revision ID: 4ade61addf0b
Revises: e5b313ec6123
Create Date: 2023-06-04 23:59:25.771567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4ade61addf0b"
down_revision = "e5b313ec6123"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("postings", sa.Column("active", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("postings", "active")
    # ### end Alembic commands ###
