"""init database

Revision ID: 672291ebcf13
Revises: 4ade61addf0b
Create Date: 2023-06-05 00:48:19.083790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "672291ebcf13"
down_revision = "4ade61addf0b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("feeds", sa.Column("active", sa.Boolean(), nullable=True))
    op.drop_column("postings", "active")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("postings", sa.Column("active", sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column("feeds", "active")
    # ### end Alembic commands ###
